CREATE TABLE users (
  id                    CHAR(36)          NOT NULL,             -- UUID, generated by the app
  tenant_id             CHAR(36)          NOT NULL,             -- the school this account belongs to
  email                 VARCHAR(255)      NOT NULL,             -- stored lower-case
  password_hash         VARCHAR(255)      NOT NULL,             -- bcrypt is 60 chars; room to move to Argon2
  role_id               TINYINT UNSIGNED  NOT NULL,
  failed_login_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  locked_until          DATETIME          NULL,                 -- NULL = not locked (UTC)
  is_active             BOOLEAN           NOT NULL DEFAULT TRUE,
  created_at            DATETIME          NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME          NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  -- One email per school. This UNIQUE constraint is also the index used by login lookups.
  CONSTRAINT uq_users_tenant_email UNIQUE (tenant_id, email),
  KEY idx_users_role_id (role_id),
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
