CREATE TABLE refresh_tokens (
  id          CHAR(36) NOT NULL,                            -- UUID, generated by the app
  user_id     CHAR(36) NOT NULL,
  token_hash  CHAR(64) NOT NULL,                            -- SHA-256 (hex) of the token; the raw token is never stored
  family_id   CHAR(36) NOT NULL,                            -- all tokens from one login share a family
  expires_at  DATETIME NOT NULL,                            -- UTC
  revoked_at  DATETIME NULL,                                -- NULL = still usable
  replaced_by CHAR(36) NULL,                                -- the token issued when this one was rotated
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
  KEY idx_refresh_tokens_user_id (user_id),
  KEY idx_refresh_tokens_family_id (family_id),
  KEY idx_refresh_tokens_replaced_by (replaced_by),
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_refresh_tokens_replaced_by FOREIGN KEY (replaced_by) REFERENCES refresh_tokens (id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
