-- One row per login session. Every refresh token issued by rotating that session's tokens
-- belongs to the same family, so the user is stored here once instead of on every token
-- (003 stored user_id on refresh_tokens, which broke 3NF: family_id -> user_id).
CREATE TABLE token_families (
  id         CHAR(36) NOT NULL,                             -- UUID, generated by the app
  user_id    CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,   -- when the user logged in (UTC)
  revoked_at DATETIME NULL,                                 -- NULL = session active; set on logout or token reuse
  PRIMARY KEY (id),
  KEY idx_token_families_user_id (user_id),
  CONSTRAINT fk_token_families_user FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
